name: uapp
description: "Internal App for Unichem Candi Indonesia"

publish_to: 'none'

version: 0.1.0+7

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  speech_to_text: ^6.6.1
  intl: ^0.19.0
  http: ^1.2.1
  sqflite: ^2.3.3+1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  webview_flutter: ^4.8.0
  dropdown_search: ^5.0.6
  camera: ^0.11.0+1
  hand_signature: ^3.0.3
  connectivity_plus: ^6.0.3
  image: ^4.2.0
  permission_handler: ^11.3.1
  file_picker: ^8.0.3
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^9.0.0
  android_alarm_manager_plus: ^3.0.2
  screen_brightness: ^1.0.1
  remove_bg: ^0.0.3
  flutter_bloc: ^8.1.6
  flutter_quill: ^9.5.14
  quill_html_converter: ^9.5.14
  flutter_html: ^3.0.0-beta.2
  flutter_cached_pdfview: ^0.4.2
  flutter_downloader: ^1.11.7
  html: ^0.15.4
  flutter_barcode_scanner: ^2.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  flutter_foreground_task: ^8.17.0
  workmanager: ^0.5.2
  device_apps: ^2.2.0
  firebase_messaging: ^15.2.1
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
